on:
  - push
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      postgres:
        image: postgres:13.3-alpine
        env:
          POSTGRES_PASSWORD: verysecure
          POSTGRES_USER: dev
          POSTGRES_DB: cocktails
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build application
        run: ./gradlew -Pci classes testClasses
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ github.token }}
      - name: Test application
        run: ./gradlew -Pci test
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ github.token }}
      - name: Push branch docker image
        if: ${{ github.event_name == 'push' }}
        run: ./gradlew -Pci jib -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ github.token }}
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ github.token }}
